version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: exodus-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: food
      MARIADB_USER: test
      MARIADB_PASSWORD: test1234
      MARIADB_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: exodus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  mariadb_data:
  redis_data:
